baseURL = 'https://mortworks.github.io/teach-blog/'
languageCode = 'en-us'
title = "PWM Teach-Blog"
theme = 'PaperMod'

[params]
showPostNavLinks = true
showReadingTime = true
showToc = true
showFullContent = false
